### ISSUE TITLE
lowpolify webapp not working, "throw new ERR_INVALID_CALLBACK();"

### ISSUE THREAD

**Issue by AlienKevin** [ghostwriternr/lowpolify#8]
Hi, when I try to process an image on webapp, the cmd displays an error. Here's the full message:
```
Kevin Li (master) lowpolify $ node server.js
The magic begins on port 8080
A user connected
Hello server! from 8l4gVm3ZEEekOn3uAAAA
GET /slider_module/rzslider.min.css 304 3.529 ms - -
GET /upload_module/ng-file-upload-all.min.js 304 0.819 ms - -
GET /slider_module/rzslider.min.js 304 1.016 ms - -
A user connected
Hello server! from uTrnwE4ilNFqA3TPAAAB
GET /favicon.ico 304 1.641 ms - -
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:936:14)
    at C:\Users\Kevin Li\Desktop\lowpolify\app\routes\index.js:27:24
    at Array.forEach (<anonymous>)
    at C:\Users\Kevin Li\Desktop\lowpolify\app\routes\index.js:21:15
    at FSReqWrap.oncomplete (fs.js:141:20)
```
I successfully copied the image to the webapp but it can't process it.

**Comment by AlienKevin** [comment]
I figured out that I forget to build the dependencies and now the python script works. However, the output is a black rectangle for the images I tested. I don't know how cfraction works so I tried values like 0.001, 0.1, 10, 80, etc. but the output is still a black rectangle. Can anyone help me?
